### PR TITLE
Added Terminal and Line Comments

### PR DESCRIPTION
**Pull request by sverrisson**
Added Terminal and Line Comments
// -> Toggles line comments
Term -> Toggles the builtin terminal

### CODE REVIEW

**Comment by ashhitch** [comment]
Hi, @sverrisson  thanks for PR!
I really like the idea of adding the built-in terminal as a button. However, I am not sure that comment toggling fits with this plugin which all about commands rather than directly authoring code.
Would you consider changing you PR to just be the terminal toggle?

In the future, I would like to add the ability to turn these button on and off via the user settings maybe that would be a good time to add extra features.

**Comment by ashhitch** [comment]
@sverrisson Sorry I merged your branch in rather than mine so had to revert it to apply my changes.  I cant reopen it but if you wanted to add in the terminal toggle then please reopen a pull request. 

Sorry for the inconvenience!

**Comment by sverrisson** [comment]
Hi, Thanks for Merging. I could have done the changes requested when home from work as I don't have TouchId on the machine here.

**Comment by ashhitch** [comment]
@sverrisson Looks like we commented at the same time, just in case you didn't spot it. 
The merge was done in error so had to revert it, I have updated the extension to include optional configuration of the buttons, please feel free to add your terminal toggle back in a new pull request when you home.

 **Once again sorry for the inconvenience and thanks for contributing to the extension!**

**Pull request merged**
